-- 1. Table for Nossos Serviços
CREATE TABLE IF NOT EXISTS site_services (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_pt TEXT NOT NULL,
    title_en TEXT,
    description_pt TEXT NOT NULL,
    description_en TEXT,
    icon TEXT DEFAULT 'fas fa-star',
    display_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Table for Momentos (Videos)
CREATE TABLE IF NOT EXISTS site_momentos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    video_url TEXT NOT NULL,
    display_order INT DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Extend Site Settings for Marketing & SEO
INSERT INTO site_settings (key, value) VALUES 
('marketing_fb_pixel_id', ''),
('marketing_google_analytics_id', ''),
('seo_title', 'Divinos Graffic | Criatividade em Memórias'),
('seo_description', 'Transformamos momentos especiais em memórias eternas com quadros, brindes e design personalizado.'),
('seo_keywords', 'gráfica, quadros personalizados, brindes, design, divinos graffic, memórias')
ON CONFLICT (key) DO NOTHING;

-- 4. Enhance Page Visits for Advanced Analytics
-- Drop old table if needed to rebuild with new columns, or just add them
ALTER TABLE page_visits ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE page_visits ADD COLUMN IF NOT EXISTS region TEXT;
ALTER TABLE page_visits ADD COLUMN IF NOT EXISTS city TEXT;
ALTER TABLE page_visits ADD COLUMN IF NOT EXISTS device_type TEXT;
ALTER TABLE page_visits ADD COLUMN IF NOT EXISTS browser TEXT;
ALTER TABLE page_visits ADD COLUMN IF NOT EXISTS os TEXT;

-- 5. Enable RLS for new tables
ALTER TABLE site_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_momentos ENABLE ROW LEVEL SECURITY;

-- 6. RLS Policies
CREATE POLICY "Public Read Services" ON site_services FOR SELECT USING (true);
CREATE POLICY "Admin All Services" ON site_services FOR ALL USING (auth.role() = 'authenticated');

CREATE POLICY "Public Read Momentos" ON site_momentos FOR SELECT USING (true);
CREATE POLICY "Admin All Momentos" ON site_momentos FOR ALL USING (auth.role() = 'authenticated');

-- 7. Seed initial data for Services (based on current index.html)
INSERT INTO site_services (title_pt, title_en, description_pt, description_en, icon, display_order) VALUES
('Impressão & Personalização', 'Printing & Customization', '• Impressão de fotografias e quadros personalizados\n• Convites para casamentos\n• Placas personalizadas\n• Banners e Roll Up\n• Vinil e Contravision\n• Flyers e folhetos', '• Printing of personalized photos and frames\n• Wedding invitations\n• Custom signs\n• Banners and roll ups\n• Vinyl and contravision\n• Flyers and brochures', 'fas fa-print', 1),
('Design & Produção Visual', 'Design & Visual Production', '• Molduras e quadros em foam\n• Telas decorativas\n• Molduras de vidro e de pedra\n• Chavenas e chaveiros personalizados\n• Estampagem de tecidos\n• Criação de logotipos e identidade visual', '• Frames and foam boards\n• Decorative canvases\n• Glass and stone frames\n• Personalized mugs and keychains\n• Fabric printing\n• Logo and brand identity creation', 'fas fa-palette', 2),
('Identidade Corporativa', 'Office Material & Corporate Identity', '• Cartões de visita\n• Papel timbrado\n• Bordados e carimbos\n• VD’s e recibos\n• Livros de fatura\n• Cartazes e posters', '• Business cards\n• Letterheads\n• Embroidery and stamps\n• Receipts and vouchers\n• Invoice books\n• Posters and signage', 'fas fa-briefcase', 3);

-- 8. Seed initial data for Momentos (based on current index.html)
INSERT INTO site_momentos (video_url, display_order) VALUES
('videos/video1 (1).mp4', 1),
('videos/video1 (2).mp4', 2),
('videos/video1 (6).mp4', 3);
