-- Create table for tracking page visits
CREATE TABLE IF NOT EXISTS page_visits (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_url TEXT,
  user_agent TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE page_visits ENABLE ROW LEVEL SECURITY;

-- Allow public to insert (track stats)
CREATE POLICY "Public Insert Visits" ON page_visits FOR INSERT WITH CHECK (true);

-- Allow admins to read analytics
CREATE POLICY "Admins Read Visits" ON page_visits FOR SELECT USING (auth.role() = 'authenticated');
