-- TABELA PARA ITENS DO CARROSSEL HERO
CREATE TABLE IF NOT EXISTS carousel_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    image_url TEXT NOT NULL,
    title TEXT, -- Nome do produto/membro
    subtitle TEXT, -- Cargo/descrição
    display_order INT DEFAULT 0,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Habilitar RLS
ALTER TABLE carousel_items ENABLE ROW LEVEL SECURITY;

-- Políticas de Acesso
CREATE POLICY "Permitir leitura pública" ON carousel_items FOR SELECT USING (true);
CREATE POLICY "Permitir tudo para admin autenticado" ON carousel_items FOR ALL USING (auth.role() = 'authenticated');

-- Inserir dados iniciais (baseados no index.html atual)
INSERT INTO carousel_items (image_url, title, subtitle, display_order) VALUES
('images/Exposição principal/exposição (1).jpg', 'Produto 1', 'Mais vendido', 1),
('images/Exposição principal/exposição (2).jpg', 'Produto 2', 'Tendência', 2),
('images/Exposição principal/exposição (3).jpg', 'Produto 3', 'Novo no site', 3),
('images/Exposição principal/exposição (4).jpg', 'Produto 4', 'Destaque', 4),
('images/Exposição principal/exposição (5).jpg', 'Produto 5', 'Edição Limitada', 5);
