-- Create categories table
CREATE TABLE IF NOT EXISTS categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT UNIQUE NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Simple way to link products to strictly existing categories (optional, but safer)
-- ALTER TABLE products ADD CONSTRAINT fk_product_category FOREIGN KEY (category) REFERENCES categories(name) ON UPDATE CASCADE;

-- Insert initial values matching current hardcoded options
INSERT INTO categories (name) VALUES 
('decoração'), 
('Canecas'), 
('Papelaria'), 
('Gráficos'), 
('Outros')
ON CONFLICT (name) DO NOTHING;
