-- Create the 'site_settings' table
CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key TEXT UNIQUE NOT NULL,
  value TEXT,
  description TEXT
);

-- Basic settings data
INSERT INTO site_settings (key, value, description) VALUES
('hero_title', 'Criatividade que Transforma Momentos', 'Title on the home page hero section'),
('hero_subtitle', 'Especializados em prestar serviços de gráfica e serigrafia de alta qualidade.', 'Subtitle on the home page hero section'),
('contact_email', 'info.divinosgraffic@gmail.com', 'Contact email address'),
('contact_phone', '+258 82 880 0311', 'Primary phone number'),
('contact_phone2', '+258 84 880 0311', 'Secondary phone number'),
('address', 'Maputo Central B, na zona da Pandora', 'Physical address'),
('whatsapp_number', '+258828800311', 'WhatsApp number for links (include country code)'),
('facebook_url', 'https://www.facebook.com/Divinosgraffic', 'Facebook URL'),
('instagram_url', 'https://www.instagram.com/divinos_graffic?igsh=MTVvYjB5ZHltazc1aw==', 'Instagram URL')
ON CONFLICT (key) DO NOTHING;

-- Create the 'products' table
CREATE TABLE IF NOT EXISTS products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT,
  price TEXT, -- Stored as text to allow "500 MT" or "Sob Consulta"
  category TEXT, -- 'decoração', 'Canecas', 'Papelaria', 'Gráficos'
  image_url TEXT,
  whatsapp_message TEXT, -- Custom message for the whatsapp button
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Create a storage bucket for products if it checks for existence (This usually needs to be done via UI or API, doing basic polices here)
-- NOTE: You must manually create a storage bucket named 'products-images' in the Supabase Dashboard and make it Public.

-- RLS Policies (Row Level Security)
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE products ENABLE ROW LEVEL SECURITY;

-- Allow public read access to everyone
CREATE POLICY "Public Read Settings" ON site_settings FOR SELECT USING (true);
CREATE POLICY "Public Read Products" ON products FOR SELECT USING (true);

-- Allow authenticated users (Admin) to insert/update/delete
CREATE POLICY "Admin All Settings" ON site_settings USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
CREATE POLICY "Admin All Products" ON products USING (auth.role() = 'authenticated') WITH CHECK (auth.role() = 'authenticated');
